baseURL = "https://defensive-lab.agency/"
languageCode = "en-us"
title = "Defensive Lab Agency"
relativeURLs = true
canonifyurls = true
paginate = 25
theme = "bare"
defaultContentLanguageInSubdir= true
enableRobotsTXT = true



[permalinks]
  post = "/:year/:month/:slug/"

[params]
mainSections = ["post"]
author = "Defensive Lab Agency"
